# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b74713fa2ed5e6fec7c335195b4fb9a9d0f95c96adcb5966de71a5d94090adbf6bfc1b23459649958858a09f74db22ae8a368bd4bf693b27d1a1e55725615ea

test:
  secret_key_base: 2eeee78010f56026f01969aa01f32b8bf9a5f79868cd0f6679852a65879105ad343ed6de6b5d3c21de1b17d3accd5986dd07ab8fdb415e1b6a1b7909fa8f31dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
